/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Tokens that switch between light/dark are driven by CSS variables
        // (see src/index.css). Everything else below stays static.
        surface: "rgb(var(--c-surface) / <alpha-value>)",
        "surface-variant": "rgb(var(--c-surface-variant) / <alpha-value>)",
        "surface-container": "rgb(var(--c-surface-container) / <alpha-value>)",
        "surface-container-low": "rgb(var(--c-surface-container-low) / <alpha-value>)",
        "surface-container-high": "rgb(var(--c-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--c-surface-container-highest) / <alpha-value>)",
        "on-surface": "rgb(var(--c-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--c-on-surface-variant) / <alpha-value>)",
        primary: "rgb(var(--c-primary) / <alpha-value>)",
        "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--c-primary-container) / <alpha-value>)",
        secondary: "rgb(var(--c-secondary) / <alpha-value>)",
        "on-secondary": "rgb(var(--c-on-secondary) / <alpha-value>)",
        "outline-variant": "rgb(var(--c-outline-variant) / <alpha-value>)",
        error: "rgb(var(--c-error) / <alpha-value>)",

        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "tertiary-fixed-dim": "#c3c8bd",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#ffddb6",
        "on-tertiary-fixed-variant": "#434840",
        "on-secondary-container": "#785e3e",
        "primary-fixed": "#e4e2e1",
        "secondary-fixed-dim": "#e2c19b",
        "on-secondary-fixed-variant": "#594325",
        "on-primary-fixed-variant": "#474747",
        "surface-bright": "#fbf9f4",
        "inverse-on-surface": "#f2f1ec",
        background: "#fbf9f4",
        "secondary-container": "#fddab2",
        "on-primary-container": "#949393",
        "inverse-primary": "#c8c6c5",
        "on-primary-fixed": "#1b1c1c",
        "surface-dim": "#dbdad5",
        outline: "#747878",
        "on-error": "#ffffff",
        "on-background": "#1b1c19",
        "tertiary-fixed": "#e0e4d9",
        "on-tertiary-fixed": "#181d16",
        "on-secondary-fixed": "#291801",
        "inverse-surface": "#30312e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#91958b",
        "on-error-container": "#93000a",
        tertiary: "#151913",
        "tertiary-container": "#292e26",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        unit: "8px",
        gutter: "24px",
        "section-gap": "80px",
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
